"use client";
import {useState} from "react";
import {useI18n} from "@/components/i18n-provider";

const gameLogPath=String.raw`%USERPROFILE%\AppData\LocalLow\First Day Games\Deskrawl`;

const copy:Record<string,{title:string;body:string;limits:string;yourLog:string;step1:string;copyPath:string;step2:string;drop:string;reading:string;orElse:string;choose:string;chooseHelp:string}>={
 en:{title:"What this tracker does",body:"It reads the Game.log file that Deskrawl writes on your PC, and only that file. It works out your level, the XP you still need, your XP, gold and items per hour, and the stage you are farming. It all happens in your browser: we do not send your log, or anything worked out from it, to any server, and this page loads nothing from any other site. It never opens your save file and does not touch the game or your account. If you close the tab, it stops reading.",limits:"Limits: the hourly pace needs about 10 minutes of play; the stage shows on Normal only, except the one you start the game on; the log says your class only when the game starts with a character that is not new.",yourLog:"Your Game.log",step1:"Press Windows + R, paste this path and press Enter. Deskrawl's folder opens.",copyPath:"Copy path",step2:"Drag Game.log from that folder onto the tracker below.",drop:"Drop Game.log here",reading:"The page keeps reading it while you play when your browser gives us a live file handle.",orElse:"Or else",choose:"Choose Game.log",chooseHelp:"It opens a window to look for the file: paste the same path into its address bar, press Enter and pick Game.log."},
 fr:{title:"Ce que fait ce tracker",body:"Il lit uniquement le fichier Game.log que Deskrawl écrit sur ton PC. Il essaie d'en tirer ton niveau, l'XP qu'il te reste, ton rythme d'XP, d'or et d'objets par heure, ainsi que la zone farmée. Tout se passe dans ton navigateur : le log et les données calculées ne sont envoyés à aucun serveur. Le tracker n'ouvre jamais ta sauvegarde et ne touche ni au jeu ni à ton compte. Fermer l'onglet arrête la lecture.",limits:"Limites : les rythmes horaires ont besoin d'environ 10 minutes de jeu ; la zone est surtout fiable en Normal, sauf celle présente au lancement ; la classe n'apparaît dans le log que dans certaines séquences de démarrage.",yourLog:"Ton Game.log",step1:"Appuie sur Windows + R, colle ce chemin puis appuie sur Entrée. Le dossier Deskrawl s'ouvre.",copyPath:"Copier le chemin",step2:"Fais glisser Game.log depuis ce dossier vers le tracker ci-dessous.",drop:"Dépose Game.log ici",reading:"La page continue de le relire pendant que tu joues lorsque le navigateur nous fournit un accès fichier persistant.",orElse:"Sinon",choose:"Choisir Game.log",chooseHelp:"Une fenêtre s'ouvre : colle le même chemin dans sa barre d'adresse, Entrée, puis sélectionne Game.log."},
 de:{title:"Was der Tracker macht",body:"Er liest ausschließlich die Game.log-Datei, die Deskrawl auf deinem PC schreibt. Daraus ermittelt er Level, fehlende XP, XP/Gold/Items pro Stunde und die gefarmte Stage. Alles bleibt im Browser; weder Log noch Ergebnisse werden an einen Server gesendet. Save-Dateien, Spiel und Account werden nicht verändert.",limits:"Grenzen: Stundenraten brauchen etwa 10 Minuten Spielzeit; die Stage-Erkennung ist vor allem auf Normal zuverlässig; die Klasse steht nur in bestimmten Startzeilen des Logs.",yourLog:"Deine Game.log",step1:"Windows + R drücken, diesen Pfad einfügen und Enter drücken.",copyPath:"Pfad kopieren",step2:"Game.log aus dem Ordner auf den Tracker ziehen.",drop:"Game.log hier ablegen",reading:"Bei unterstütztem Live-Dateizugriff wird die Datei während des Spielens erneut gelesen.",orElse:"Oder",choose:"Game.log wählen",chooseHelp:"Im Dateifenster denselben Pfad in die Adressleiste einfügen und Game.log auswählen."},
 es:{title:"Qué hace este tracker",body:"Lee únicamente el archivo Game.log que Deskrawl escribe en tu PC. Calcula nivel, XP restante, XP/oro/objetos por hora y la fase que estás farmeando. Todo ocurre en el navegador; no enviamos el log ni los resultados a ningún servidor y nunca tocamos tu guardado, el juego o tu cuenta.",limits:"Límites: los ritmos por hora necesitan unos 10 minutos; la fase es más fiable en Normal; la clase solo aparece en algunas líneas de inicio.",yourLog:"Tu Game.log",step1:"Pulsa Windows + R, pega esta ruta y pulsa Enter.",copyPath:"Copiar ruta",step2:"Arrastra Game.log desde esa carpeta al tracker.",drop:"Suelta Game.log aquí",reading:"Con acceso persistente al archivo, la página lo vuelve a leer mientras juegas.",orElse:"O",choose:"Elegir Game.log",chooseHelp:"En la ventana de archivos pega la misma ruta en la barra de direcciones y elige Game.log."},
 "zh-CN":{title:"这个追踪器会做什么",body:"它只读取 Deskrawl 在你电脑上写入的 Game.log。它会尝试计算等级、升级所需 XP、每小时 XP/金币/物品以及当前刷的关卡。所有处理都在浏览器本地完成，不上传日志或计算结果，也不会读取存档、修改游戏或账号。",limits:"限制：每小时速度大约需要 10 分钟游戏数据；关卡识别主要在 Normal 难度可靠；职业只会出现在部分启动日志中。",yourLog:"你的 Game.log",step1:"按 Windows + R，粘贴下面路径并回车。",copyPath:"复制路径",step2:"把 Game.log 从该目录拖到下面的追踪器。",drop:"把 Game.log 拖到这里",reading:"浏览器支持持续文件访问时，页面会在你游戏时继续读取。",orElse:"或者",choose:"选择 Game.log",chooseHelp:"在文件窗口地址栏粘贴相同路径，回车后选择 Game.log。"},
 ja:{title:"このトラッカーがすること",body:"Deskrawl がPCに書き出す Game.log だけを読みます。レベル、次までのXP、XP/ゴールド/アイテム毎時、周回中のステージを推定します。処理はブラウザ内だけで行い、ログや計算結果をサーバーへ送りません。セーブ、ゲーム、アカウントには触れません。",limits:"制限：毎時レートには約10分のプレイが必要です。ステージ判定は主にNormalで有効で、クラスは一部の起動ログにしか出ません。",yourLog:"Game.log",step1:"Windows + R を押し、下のパスを貼り付けて Enter。",copyPath:"パスをコピー",step2:"そのフォルダの Game.log を下のトラッカーへドラッグ。",drop:"Game.log をここへドロップ",reading:"ブラウザが継続アクセスを許可した場合、プレイ中も再読込します。",orElse:"または",choose:"Game.log を選択",chooseHelp:"ファイル画面のアドレスバーに同じパスを貼り付け、Game.log を選びます。"},
 ko:{title:"이 트래커가 하는 일",body:"Deskrawl이 PC에 기록하는 Game.log만 읽습니다. 레벨, 다음 레벨까지 XP, 시간당 XP/골드/아이템, 파밍 스테이지를 계산하려고 합니다. 모든 처리는 브라우저 안에서 이뤄지며 로그나 계산 결과를 서버로 보내지 않습니다. 세이브 파일, 게임, 계정은 건드리지 않습니다.",limits:"제한: 시간당 속도는 약 10분의 플레이가 필요하며 스테이지 감지는 주로 Normal에서 신뢰할 수 있습니다. 클래스는 일부 시작 로그에만 기록됩니다.",yourLog:"내 Game.log",step1:"Windows + R을 누르고 아래 경로를 붙여넣은 뒤 Enter.",copyPath:"경로 복사",step2:"폴더의 Game.log를 아래 트래커로 드래그하세요.",drop:"Game.log를 여기에 놓기",reading:"브라우저가 지속 파일 접근을 허용하면 플레이 중에도 계속 다시 읽습니다.",orElse:"또는",choose:"Game.log 선택",chooseHelp:"파일 창 주소 표시줄에 같은 경로를 붙여넣고 Game.log를 선택하세요."},
 pl:{title:"Co robi tracker",body:"Czyta wyłącznie plik Game.log zapisywany przez Deskrawl na twoim PC. Próbuje wyliczyć poziom, brakujące XP, XP/złoto/przedmioty na godzinę oraz farmiony etap. Wszystko dzieje się w przeglądarce; nic nie jest wysyłane na serwer i tracker nie dotyka zapisu gry ani konta.",limits:"Ograniczenia: tempo godzinowe potrzebuje ok. 10 minut gry; etap jest najpewniejszy na Normal; klasa pojawia się tylko w części linii startowych.",yourLog:"Twój Game.log",step1:"Naciśnij Windows + R, wklej tę ścieżkę i Enter.",copyPath:"Kopiuj ścieżkę",step2:"Przeciągnij Game.log z folderu na tracker.",drop:"Upuść Game.log tutaj",reading:"Przy trwałym dostępie do pliku strona czyta go ponownie podczas gry.",orElse:"Lub",choose:"Wybierz Game.log",chooseHelp:"W oknie plików wklej tę samą ścieżkę w pasek adresu i wybierz Game.log."},
 "pt-BR":{title:"O que este tracker faz",body:"Ele lê somente o Game.log que o Deskrawl grava no seu PC. Tenta calcular nível, XP restante, XP/ouro/itens por hora e a fase farmada. Tudo acontece no navegador; nada é enviado para servidor e o tracker não abre seu save nem mexe no jogo ou conta.",limits:"Limites: as taxas por hora precisam de cerca de 10 minutos; a fase é mais confiável no Normal; a classe aparece apenas em algumas linhas de início.",yourLog:"Seu Game.log",step1:"Pressione Windows + R, cole este caminho e Enter.",copyPath:"Copiar caminho",step2:"Arraste Game.log dessa pasta para o tracker.",drop:"Solte Game.log aqui",reading:"Com acesso persistente ao arquivo, a página continua relendo enquanto você joga.",orElse:"Ou",choose:"Escolher Game.log",chooseHelp:"Na janela de arquivos cole o mesmo caminho na barra de endereço e selecione Game.log."},
 ru:{title:"Что делает трекер",body:"Он читает только Game.log, который Deskrawl пишет на вашем ПК. Пытается определить уровень, недостающий XP, XP/золото/предметы в час и фармимый этап. Всё обрабатывается в браузере; лог и расчёты не отправляются на сервер, сохранение, игра и аккаунт не меняются.",limits:"Ограничения: для темпа в час нужно около 10 минут игры; этап надёжнее определяется на Normal; класс есть только в некоторых стартовых строках.",yourLog:"Ваш Game.log",step1:"Нажмите Windows + R, вставьте путь и Enter.",copyPath:"Копировать путь",step2:"Перетащите Game.log из папки в трекер.",drop:"Перетащите Game.log сюда",reading:"Если браузер даёт постоянный доступ к файлу, страница перечитывает его во время игры.",orElse:"Или",choose:"Выбрать Game.log",chooseHelp:"В окне выбора вставьте тот же путь в адресную строку и выберите Game.log."}
};

export function TrackerGuide(){
 const {locale}=useI18n(); const text=copy[locale]??copy.en; const [copied,setCopied]=useState(false);
 async function copyPath(){await navigator.clipboard.writeText(gameLogPath);setCopied(true);setTimeout(()=>setCopied(false),1400)}
 return <section className="tracker-guide">
  <article className="game-card tracker-explainer">
   <div className="eyebrow">LOCAL ONLY · GAME.LOG</div><h2>{text.title}</h2><p>{text.body}</p><p className="tracker-limits"><strong>Limits:</strong> {text.limits.replace(/^Limits:\s*/,"")}</p>
  </article>
  <article className="game-card tracker-howto">
   <div className="eyebrow">01 · WINDOWS</div><h2>{text.yourLog}</h2>
   <p><strong>1.</strong> {text.step1}</p>
   <div className="path-box"><code>{gameLogPath}</code><button type="button" className="game-btn gold" onClick={copyPath}>{copied?"✓":text.copyPath}</button></div>
   <p><strong>2.</strong> {text.step2}</p>
   <div className="drop-preview">{text.drop}<small>{text.reading}</small></div>
   <p className="muted"><strong>{text.orElse}:</strong> {text.choose} — {text.chooseHelp}</p>
  </article>
 </section>
}
